Jadu_Blog/Jadu_Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

Jadu_Blog/blog/urls.py
from django.urls import path
from blog import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .forms import MyPasswordResetForm,MySetPasswordForm
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.Home_View, name='home'),
    path('about/',views.About_View, name='about'),
    path('contact/',views.Contact_View, name='contact'),
    path('dashboard/',views.Dashboard_View, name='dashboard'),
    path('login/',views.Login_View, name='login'),
    path('signup/',views.Signup_View, name='singup'),
    path('logout/',views.Logout_View, name='logout'),

    # password forget
    path('password-reset/', PasswordResetView.as_view(template_name='blog/forgetpassword.html', form_class=MyPasswordResetForm), name='password_reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(template_name='blog/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='blog/password_reset_confirm.html',form_class=MySetPasswordForm), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='blog/password_reset_complete.html'), name='password_reset_complete'),

    # Add Post
    path('addpost/', views.Add_Post, name='addpost'),
    # update post
    path('updatepost/<int:id>/', views.Update_Post, name='updatepost'),
    # Delete Post
    path('delete/<int:id>/', views.Delete_Post, name='deletepost'),
    # User Profile
    path('userprofile/',views.User_Profile_View, name='userprofile')
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Jadu_Blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=150)
    desc = models.TextField()
    class Meta:
        db_table = 'Post'

class Contact(models.Model):
    name = models.CharField(max_length=64)
    email = models.EmailField()
    mob = models.IntegerField()
    address = models.CharField(max_length=80)
    
    class Meta:
        db_table = 'contact'
    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, primary_key=True)
    image = models.ImageField(upload_to='porductimage')
    
    def __str__(self):
        return self.user.username
    
    class Meta:
        db_table = 'userprofile'

Jadu_Blog/blog/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordResetForm, SetPasswordForm
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext, gettext_lazy as _
from django.core.exceptions import ValidationError
from django.contrib.auth import password_validation
from .models import Post, Contact, UserProfile

def validate_email(value):
    if User.objects.filter(email = value).exists():
        raise ValidationError((f'{value} alredy taken'), params ={'value':value})

class SignupForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Confirm Password(Again)', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    email = forms.CharField(required= True, label='Email Id', validators=[validate_email],widget=forms.EmailInput(attrs={'class':'form-control'}))

    
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']
        labels = {
            'first_name':'First Name',
            'last_name':'Last Name',
        }
        widgets= {
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
        }

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus':True, 'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'}))

    # password forget
class MyPasswordResetForm(PasswordResetForm):
    email = forms.CharField(required= True, label='Email Id', widget=forms.EmailInput(attrs={'class':'form-control'}))

    def clean_email(self):
        email_id = self.cleaned_data['email']
        if not User.objects.filter(email__iexact=email_id).exists():
            raise ValidationError('This is not Existing user, please Enter Existing Email')
        return email_id

class MySetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label='New Password', strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'new-password', 'class':'form-control'}), help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label='Confirm New Password', strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'new-password', 'class':'form-control'}))

class MyPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        labels = {
            'title':'Title',
            'desc':'Description'
        }
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'desc':forms.Textarea(attrs={'class':'form-control'}),
        }
    
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
        labels ={
            'name':'Name',
            'email':'Email Address',
            'mob':'Mobile Number',
            'address':'Address'
        }
        widgets ={
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'mob':forms.NumberInput(attrs={'class':'form-control'}),
            'address':forms.TextInput(attrs={'class':'form-control'})
        }
    
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('image',)
        labels = {'image':'Upload Image:'}
  

Jadu_Blog/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import SignupForm, LoginForm, MyPostForm, ContactForm, UserProfileForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import Post, UserProfile
from django.contrib.auth.models import User, Group



def Home_View(request):
    posts = Post.objects.all()
    return render(request, 'blog/home.html', {'posts':posts})

def About_View(request):
    return render(request, 'blog/about.html')

def Contact_View(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            print('Data:', form.cleaned_data)
            form.save()
            messages.success(request,'thanks for fill the form!!')
            return render(request,'blog/singup.html')
    return render(request, 'blog/contact.html',{'forms':form})

def Dashboard_View(request):
    if request.user.is_authenticated:
        posts = Post.objects.all()
        user = request.user
        print('user:',user)
        user_profile = User.objects.filter(username=user)
        # print(f'User Profile: {user_profile}')
        # for user in user_profile:
        #     print('id:',user.id)
        #     print('profile pic:', user.userprofile.image.url)
        full_name = user.get_full_name()
        gps = user.groups.all()
        return render(request, 'blog/dashboard.html', {'posts':posts, 'full_name':full_name,'groups':gps, 'user_profile':user_profile})
    else:
        return HttpResponseRedirect('/login/')

def Login_View(request):
    if not request.user.is_authenticated:
        form = LoginForm()
        if request.method == 'POST':
            form = LoginForm(request=request, data=request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                upass = form.cleaned_data['password']
                user = authenticate(username=uname, password=upass)
                if user is not None:
                    login(request, user)
                    messages.success(request, 'You Are Login Now!!')
                    return HttpResponseRedirect('/dashboard/')
        return render(request, 'blog/login.html', {'forms':form})
    else:
        messages.info(request, 'Yor are already Login')
        return render(request, 'blog/dashboard.html')

def Logout_View(request):
    if request.user.is_authenticated:
        logout(request,)
        messages.info(request,'Thanks for Using Our Application')
        return render(request, 'blog/logout.html')
    else:
        return render(request, 'blog/logout.html')

def Signup_View(request):
    if not request.user.is_authenticated:
        form = SignupForm()
        if request.method == 'POST':
            form = SignupForm(request.POST)
            if form.is_valid():
                user = form.save()
                group = Group.objects.get(name='Author')
                user.groups.add(group)
                messages.success(request,'Congratulation!! Now You are an Author,')
                return render(request, 'blog/signupdone.html')
        return render(request, 'blog/singup.html',{'forms':form})
    else:
        messages.info(request, 'You are login Right Now, For creating another Account Please Logout First')
        return render(request, 'blog/dashboard.html')
    
# Add Post
def Add_Post(request):
    if request.user.is_authenticated:
        form = MyPostForm()
        if request.method == 'POST':
            form =MyPostForm(request.POST)        
            if form.is_valid():
                form.save()
                messages.success(request,'Your New Post Created Successfully!!')
                return render(request, 'blog/addpost.html')
        return render(request, 'blog/addpost.html', {'form':form})
    else:
        return HttpResponseRedirect('/login/')
    
# Update Post
def Update_Post(request, id):
    if request.user.is_authenticated:
        post_data = Post.objects.get(pk=id)
        form = MyPostForm(instance=post_data)
        if request.method == 'POST':
            form = MyPostForm(request.POST, instance=post_data)
            if form.is_valid():
                form.save()
                messages.success(request, 'Post Has Update!!')
                return render(request, 'blog/updatepost.html')
        return render(request, 'blog/updatepost.html', {'form':form})
    else:
        return HttpResponseRedirect('/login/')

# Delete Post
def Delete_Post(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            post_data = Post.objects.get(pk=id)
            post_data.delete()
            return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/login/')

# User Profile
def User_Profile_View(request):
    if request.user.is_authenticated:
        print('user:',request.user)
        form = UserProfileForm()
        if request.method == 'POST':
            form = UserProfileForm(request.POST, request.FILES)
            if form.is_valid():
                user = request.user
                image = form.cleaned_data['image']
                data = UserProfile(user=user, image=image)
                data.save()
                return HttpResponseRedirect('/dashboard/')
        return render(request,'blog/userprofile.html',{'forms':form})
    

Jadu_Blog/templates/blog/about.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}About {% endblock title %}

{% block content %}
<div class="col-sm-10">
    <h1 class="text-white my-5">About Page</h1>
    <img src="{% static 'images/deskpot.jpeg' %}" class="image--cover" alt="">
    <h3>MD WASHIM AKRAM</h3>
    <h5>(Nick Name : Jadu)</h5>
    <p>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sint voluptate placeat consequuntur beatae totam aut qui officia perspiciatis quod ratione harum ipsam sit assumenda quos atque, molestiae culpa eius nobis.
    </p>
</div>

{% endblock content %}

Jadu_Blog/templates/blog/addpost.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Add Post{% endblock title %}
{% block msg %}
   
{% endblock msg %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Post Page</h3>
    {% if messages %}
    {% for message in messages %}
    <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
    {% endfor %}
    <a href="{% url 'addpost' %}" class="btn btn-primary">Add Post</a>&nbsp;&nbsp; 
    <a href="{% url 'dashboard' %}" class="btn btn-primary">Dashboard</a>    
    {% else %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for fm in form %}
        {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br>
        {% endfor %}
        <input type="submit" class="btn btn-primary" name="" id="">&nbsp;&nbsp;
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
    </form>
    {% endif %}
</div>
{% endblock content %}

Jadu_Blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Jadublog | {% block title %} {% endblock title %} </title>
</head>
<body>
 <div class="continer-fluid bg-dark">
    {% include 'blog/navbar.html' %}
 </div>
 <div class="container">
    <div class="row">
        <div class="col-sm-12">
            {% block msg %}
            {% endblock msg %}
        </div>
    </div>
    <div class="row">
        {% block side %}
        {% endblock side %}

        {% block content %}
        {% endblock content %}
    </div>
 </div>
  <!-- Start Footer -->
  <footer id="footer" class="container-fluid bg-dark text-center p-2 mt-5">
    <small class="text-white">Copyright &copy; 2022 || Designed By Jadu || </small>
    </footer> <!-- End Footer -->   
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
</body>
</html>

Jadu_Blog/templates/blog/contact.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Contact {% endblock title %}

{% block content %}
<div class="col-sm-10">
    <h1 class="text-white my-5">Contact Page</h1>
   <form action="">
    <div class="form-row">
        <form action="" method="post" novalidate>
            {% csrf_token %}
            {% for form in forms %}
            <div class="form-group">
            {{form.label_tag}} {{form}} <small class="text-danger">{{form.errors|striptags}}</small> <br>
            </div>
            {% endfor %}
            <input type="submit" value="submit" name="" id="" class="btn btn-primary">
            {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
            <p class="alert alert-danger my-3">{{error}}</p>
            {% endfor %}
            {% endif %}
        </form>
    </div>
   </form>
</div>

{% endblock content %}

Jadu_Blog/templates/blog/dashboard.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Dashboard {% endblock title %}

{% block msg %}
    {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show my-5" {% endif %}><strong>{{message}}</strong>
        <!-- <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
    </div>
    {% endfor %}
    {% endif %}
{% endblock msg %}

{% block side %}
<div class="col-sm-2 text-white my-5 text-center">
    <h4 class="my-5">Profile</h4>
    {% for user in user_profile %}
    {% if user.userprofile.image.url %}
    <img src="{{ user.userprofile.image.url }}" class="image--cover" alt="">
    {% else %}
    <img src="{% static 'images/bydefaulprofile.jpg' %}" class="image--cover" alt="">
    {% endif %}
    {% endfor %}
    <img src="" alt="">
    <h5>{{full_name}}</h5>
    {% for group in groups %}
    <p>{{group.name}}</p>
    {% endfor %}
</div>
{% endblock side %}

{% block content %}
<div class="col-sm-10">
    <h1 class="text-white my-5">Dashboard Page</h1>
    <a href="{% url 'addpost' %}" class="btn btn-success">Add Post</a>
    <h4 class="text-center alert alert-info mt-3">Show Post Information</h4>
    {% if posts %}
    <table class="table table-hover bt-white">
        <thead>
            <tr class="text-center">
                <th scope="col" style="width: 2%;">ID</th>
                <th scope="col" style="width: 28%;">Title</th>
                <th scope="col" style="width: 55%;">Description</th>
                <th scope="col" style="width: 15%;">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr>
                <th scope="row">{{post.id}}</th>
                <th scope="row">{{post.title}}</th>
                <th scope="row">{{post.desc | linebreaks}}</th>
                <td class="text-center">
                    <a href="{% url 'updatepost' post.id %}" class="btn btn-warning btn-sm">Edit</a>
                    {% if perms.blog.delete_post %}
                    <form action="{% url 'deletepost' post.id %}" method="post" class="d-inline">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger btn-sm" value="Delete" name="" id="">
                    </form>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h1 class="text-center alert alert-warning">No Data Available</h1>
    {% endif %}
</div>

{% endblock content %}

Jadu_Blog/templates/blog/forgetpassword.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Singup{% endblock title %}

{% block content %}
<div class="col-sm-10">
    <h1 class="text-white my-5">Forget Page</h1>
    {% if messages %}
    {% for message in messages %}
    <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
    {% endfor %}
    {% endif%}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for form in form %}
        <div class="form-group">
        {{form.label_tag}} {{form}} <small class="text-danger">{{form.errors|striptags}}</small> <br>
        </div>
        {% endfor %}
        <input type="submit" value="Forget Password" name="" id="" class="btn btn-primary">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}
        {% endif %}
    </form>
</div>

{% endblock content %}

Jadu_Blog/templates/blog/home.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}

{% block title %} Home {% endblock title %}

{% block content %}
<div class="col-sm-10">
    <h1 class="text-white my-5">Home Page</h1>
    <div class="jumbotron jumbotron-fluid jumbo-color">
      {% for post in posts %}
        <div class="container">
          <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
          <p class="lead">{{post.desc |linebreaksbr}}</p> <hr> <br><br>
        </div>
      {% endfor %}
      </div>
</div>

{% endblock content %}

Jadu_Blog/templates/blog/login.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Login {% endblock title %}

{% block content %}
<div class="col-sm-10">
    <h1 class="text-white my-5">Login Page</h1>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for form in forms %}
        <div class="form-group">
        {{form.label_tag}} {{form}} <small class="text-danger">{{form.errors|striptags}}</small> <br>
        </div>
        {% endfor %}
        <input type="submit" value="Login" class="btn btn-primary" name="" id=""><br><br>
        {% if forms.non_field_errors %}
        {% for error in forms.non_field_errors %}
        <p><small class="alert alert-danger my-3">{{error}}</small></p>       
        {% endfor %}
        {% endif %}
        <a href="{% url 'password_reset' %}">Forget Password?</a>
    </form>
</div>

{% endblock content %}

Jadu_Blog/templates/blog/password_reset_confirm.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Password Reset Confirm {% endblock title %}

{% block content %}
<div class="container">
    <div class="row my-3">
           <div class="col-sm-6 offset-sm-3">
            <h1>Password Reset Confirm</h1>
            <hr>
            <form action="" method="post" novalidate>
                {% csrf_token %}
                {% for fm in form %}
                <div class="form-group">
                    {{fm.label_tag}} {{fm}} {{fm.errors|striptags}}
                </div> <br>
                {% endfor %}
                <input type="submit" value="submit" class="btn btn-primary" name="" id="">
                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                <p class="alert alert-danger">{{error}}</p>
                {% endfor %}
                {% endif %}
            </form> 
           </div>
    </div>
</div>

{% endblock content %}

Jadu_Blog/templates/blog/password_reset_done.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Singup {% endblock title %}

{% block content %}
<div class="container">
    <div class="row my-3">
            <div class="col-sm-6 offset-sm-3">
                <h4 class="alert-heading">Forget Page</h4>
                <p>An Email has been sent with instrucions to reset password <br><br>Check Your Email</p>
            </div>
    </div>
</div>

{% endblock content %}

Jadu_Blog/templates/blog/signupdone.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Singup {% endblock title %}

{% block content %}
<div class="col-sm-10">
    <h1 class="text-white my-5">Singup Page</h1>
    {% if messages %}
    {% for message in messages %}
    <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
    {% endfor %}
    {% endif%}
    <a href="{% url 'login' %}" class="btn btn-primary">Click Here for Login</a>
</div>

{% endblock content %}

Jadu_Blog/templates/blog/singup.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Singup {% endblock title %}

{% block content %}
<div class="col-sm-10">
    <h1 class="text-white my-5">Singup Page</h1>
    {% if messages %}
    {% for message in messages %}
    <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
    {% endfor %}
    {% endif%}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for form in forms %}
        <div class="form-group">
        {{form.label_tag}} {{form}} <small class="text-danger">{{form.errors|striptags}}</small> <br>
        </div>
        {% endfor %}
        <input type="submit" value="Singup" name="" id="" class="btn btn-primary">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}
        {% endif %}
    </form>
</div>

{% endblock content %}

Jadu_Blog/templates/blog/updatepost.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Update Post{% endblock title %}
{% block msg %}
   
{% endblock msg %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Update Page</h3>
    {% if messages %}
    {% for message in messages %}
    <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
    {% endfor %}
    <a href="{% url 'addpost' %}" class="btn btn-primary">Add Post</a>&nbsp;&nbsp; 
    <a href="{% url 'dashboard' %}" class="btn btn-primary">Dashboard</a>    
    {% else %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for fm in form %}
        {{fm.label_tag}} {{fm}} {{fm.errors|striptags}} <br>
        {% endfor %}
        <input type="submit" class="btn btn-primary" name="" id="">&nbsp;&nbsp;
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
    </form>
    {% endif %}
</div>
{% endblock content %}

Jadu_Blog/templates/blog/userprofile.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}User Profile {% endblock title %}

{% block content %}
<div class="col-sm-10">
    <h1 class="text-white my-5">User Image Form Page</h1>
    <form action="" method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {% for form in forms %}
        <div class="form-group">
        {{form.label_tag}} {{form}} <small class="text-danger">{{form.errors|striptags}}</small> <br>
        </div>
        {% endfor %}
        <input type="submit" value="upload" name="" id="" class="btn btn-primary">
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}
        {% endif %}
    </form>
    
</div>

{% endblock content %}